
# Path to the file with the matrices of firing rates and CVs
fpath_mats: ''

pop_names:
- L2e
- L2i
- L4e
- L4i

# Names of the parameters that vary in the batch
batch_param_names:
- ouamp
- oustd

# Batch parameter that parametrizes 1-d slice of 2-d matrix
batch_param_main: ouamp

# Method of slicing the firing rate matrix to get 1-d data
slice_method: batch_param_ratio    # oustd / ouamp = 0.4
batch_param_ratio: 0.4

# I-R mapping type and hyperparameters
map_type: richards_1d    # asymmetric sigmoid
map_params:
  x_limits:
  - 0
  - .inf
  y_limits:
  - 0
  - .inf

# Fitting bounds for I-R mapping parameters
fit_param_bounds:
  q:    # asymmetry coefficient of RICHARDS_1D mapping
  - 1
  - 10

# Limits for the input rates used for fitting
inp_limits:
  L2e:
  - 0
  - 250
  L2i:
  - 0
  - 1000
  L4e:
  - 0
  - 250
  L4i:
  - 0
  - 1000

# Parameters of the formula that determines the fitting weights
use_fit_weights: true 
fit_weight_pow: 0.5
fit_weight_limits:
- 0.1
- 10

# Parameters of the fitting algorithm
map_fit_params:
  ftol: 0.001
  max_nfev: 1000
  method: trf
  par0_kprev: 0
  return_first_guess: false
  verbose: false
  xtol: 0.0001

