batch_param_name: ext_inp_rate_common
dirpath_batch: D:\WORK\Salvador\repo\model_tuner\models\L24\exp_results\rx_batch_unconn_2
exp_name: rx_batch_unconn_2
fit_param_bounds:
  q:
  - 1
  - 10
fit_weight_limits:
- 0.1
- 10
fit_weight_pow: 0.5
inp_limits:
  L2e:
  - 0
  - 250
  L2i:
  - 0
  - 1000
  L4e:
  - 0
  - 250
  L4i:
  - 0
  - 1000
map_fit_params:
  ftol: 0.001
  max_nfev: 1000
  method: trf
  par0_kprev: 0
  return_first_guess: false
  verbose: false
  xtol: 0.0001
map_params:
  x_limits:
  - 0
  - .inf
  y_limits:
  - 0
  - .inf
map_type: richards_1d
pop_names:
- L2e
- L2i
- L4e
- L4i
rates_calc_params:
  pop_names: null
  time_limits:
  - 0.5
  - null
spikes_calc_params:
  combine_cells: true
  ms: false
  ndigits: 6
  pop_names: null
  subtract_t0: true
  time_limits:
  - 0
  - null
use_fit_weights: true
